In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("Countries.csv")

In [6]:
df.head()

,Country,Capital,Continent,Population,Area_km2,GDP_Billion_USD,Official_Language,Currency,Life_Expectancy,Literacy_Rate
0,India,New Delhi,Asia,1428000000,3287263,3730,Hindi,Indian Rupee,70.8,77.7
1,China,Beijing,Asia,1411750000,9596961,17700,Chinese,Yuan,78.2,97.2
2,United States,Washington D.C.,North America,339996563,9833517,26950,English,US Dollar,77.5,99.0
3,Indonesia,Jakarta,Asia,277534122,1904569,1390,Indonesian,Rupiah,71.7,96.0
4,Pakistan,Islamabad,Asia,240485658,881913,375,Urdu,Pakistani Rupee,66.1,62.3

In [7]:
df.tail()

,Country,Capital,Continent,Population,Area_km2,GDP_Billion_USD,Official_Language,Currency,Life_Expectancy,Literacy_Rate
45,North Korea,Pyongyang,Asia,26160821,120540,Korean,Won,73.3,100.0,NaN
46,Taiwan,Taipei,Asia,23923276,36197,790,Chinese,New Taiwan Dollar,81.3,98.9
47,Sri Lanka,Colombo,Asia,21893579,65610,84,Sinhala,Sri Lankan Rupee,77.0,92.0
48,Netherlands,Amsterdam,Europe,17942595,41543,1010,Dutch,Euro,82.2,99.0
49,Chile,Santiago,South America,19629590,756102,344,Spanish,Chilean Peso,80.0,96.4

In [8]:
df.shape

(50, 10)

In [9]:
df.columns

Index(['Country', 'Capital', 'Continent', 'Population', 'Area_km2',
       'GDP_Billion_USD', 'Official_Language', 'Currency', 'Life_Expectancy',
       'Literacy_Rate'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country            50 non-null     object
 1   Capital            50 non-null     object
 2   Continent          50 non-null     object
 3   Population         50 non-null     int64
 4   Area_km2           50 non-null     int64
 5   GDP_Billion_USD    50 non-null     object
 6   Official_Language  50 non-null     object
 7   Currency           50 non-null     object
 8   Life_Expectancy    50 non-null     float64
 9   Literacy_Rate      49 non-null     float64
dtypes: float64(2), int64(2), object(6)
memory usage: 4.0+ KB

In [11]:
df.describe()

         Population      Area_km2  Life_Expectancy  Literacy_Rate
count  5.000000e+01  5.000000e+01        50.000000      49.000000
mean   1.341062e+08  1.989176e+06        74.824000      87.444898
std    2.746084e+08  3.414999e+06         7.696873      15.160943
min    1.794260e+07  3.619700e+04        55.800000      43.000000
25%    3.462835e+07  3.309052e+05        70.800000      75.600000
50%    4.824117e+07  6.278650e+05        76.150000      95.400000
75%    1.161822e+08  1.826600e+06        79.675000      99.000000
max    1.428000e+09  1.709824e+07       100.000000     100.000000

In [12]:
df.dtypes

Country               object
Capital               object
Continent             object
Population             int64
Area_km2               int64
GDP_Billion_USD       object
Official_Language     object
Currency              object
Life_Expectancy      float64
Literacy_Rate        float64
dtype: object

In [13]:
df.isnull().sum()

Country              0
Capital              0
Continent            0
Population           0
Area_km2             0
GDP_Billion_USD      0
Official_Language    0
Currency             0
Life_Expectancy      0
Literacy_Rate        1
dtype: int64

In [14]:
df.nunique()

Country              50
Capital              50
Continent             6
Population           50
Area_km2             50
GDP_Billion_USD      50
Official_Language    31
Currency             45
Life_Expectancy      42
Literacy_Rate        37
dtype: int64

In [15]:
df.sample(5)

,Country,Capital,Continent,Population,Area_km2,GDP_Billion_USD,Official_Language,Currency,Life_Expectancy,Literacy_Rate
33,Morocco,Rabat,Africa,37840044,446550,152,Arabic,Dirham,75.9,73.8
22,South Africa,Pretoria,Africa,60414495,1221037,406,English,Rand,64.9,95.0
37,Malaysia,Kuala Lumpur,Asia,34308525,330803,434,Malay,Ringgit,76.4,95.0
28,Sudan,Khartoum,Africa,48109006,1886068,34,Arabic,Sudanese Pound,66.1,60.7
0,India,New Delhi,Asia,1428000000,3287263,3730,Hindi,Indian Rupee,70.8,77.7

In [17]:
df["Capital"]

0           New Delhi
1             Beijing
2     Washington D.C.
3             Jakarta
4           Islamabad
5               Abuja
6            Brasilia
7               Dhaka
8              Moscow
9         Mexico City
10              Tokyo
11             Manila
12        Addis Ababa
13              Cairo
14              Hanoi
15             Berlin
16             Ankara
17             Tehran
18            Bangkok
19             London
20              Paris
21               Rome
22           Pretoria
23              Seoul
24             Madrid
25       Buenos Aires
26            Algiers
27               Kyiv
28           Khartoum
29            Baghdad
30              Kabul
31             Warsaw
32             Ottawa
33              Rabat
34             Riyadh
35           Tashkent
36               Lima
37       Kuala Lumpur
38             Luanda
39             Maputo
40              Accra
41              Sanaa
42          Kathmandu
43       Antananarivo
44           Canberra
45          Pyongyang
46             Taipei
47            Colombo
48          Amsterdam
49           Santiago
Name: Capital, dtype: object

In [18]:
#Largest Population
df[df["Population"] == df["Population"].max()]

,Country,Capital,Continent,Population,Area_km2,GDP_Billion_USD,Official_Language,Currency,Life_Expectancy,Literacy_Rate
0,India,New Delhi,Asia,1428000000,3287263,3730,Hindi,Indian Rupee,70.8,77.7

In [19]:
#Countries in Europe
df[df["Continent"] == "Europe"]

,Country,Capital,Continent,Population,Area_km2,GDP_Billion_USD,Official_Language,Currency,Life_Expectancy,Literacy_Rate
8,Russia,Moscow,Europe,144444359,17098242,2240,Russian,Ruble,72.4,99.7
15,Germany,Berlin,Europe,83240525,357022,4450,German,Euro,81.2,99.0
19,United Kingdom,London,Europe,67736802,243610,3340,English,Pound Sterling,81.3,99.0
20,France,Paris,Europe,68042591,551695,3030,French,Euro,82.5,99.0
21,Italy,Rome,Europe,58870763,301340,2160,Italian,Euro,83.0,99.2
24,Spain,Madrid,Europe,48373336,505990,1580,Spanish,Euro,83.1,98.5
27,Ukraine,Kyiv,Europe,36744634,603500,160,Ukrainian,Hryvnia,71.6,99.7
31,Poland,Warsaw,Europe,36821749,312696,842,Polish,Zloty,78.5,99.8
48,Netherlands,Amsterdam,Europe,17942595,41543,1010,Dutch,Euro,82.2,99.0